server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  cloud:
    gateway:
      default-filters:
        - StripPrefix=2

      routes:
        - id: product-service
          uri: http://localhost:9090
          predicates:
            - Path=${app.api-prefix}/product/**
        - id: user-service
          uri: http://localhost:9091
          predicates:
            - Path=${app.api-prefix}/user/**
