server:
  port: 8080
  servlet:
    context-path: /product

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/xmall_product_db"
    password: root
    username: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
