server:
  port: 9091
  servlet:
    context-path: /user

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/xmall_user_db"
    password: root
    username: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
